import {
  Sun,
  Leaf,
  Droplet,
  TreePine,
  TreeDeciduous,
  Ruler,
  MapPin,
  Flower,
  Eye,
  Heart,
  ShieldCheck,
  AlertTriangle,
  Shield,
  Star,
  Clock,
  Paintbrush,
  Sprout,
  Palette,
  Pipette,
  Mountain,
  Map,
  MapPinHouse,
  Activity,
  Hand,
} from "lucide-react";

export type FilterCategory = {
  id: string;
  name: string;
  options: string[];
  icon: React.ElementType; // Use a function that returns a JSX element
};

export type FilterSection = {
  id: string;
  name: string;
  categories: FilterCategory[];
  icon: React.ElementType; // Use a function that returns a JSX element
};

export const basicFilters: FilterSection[] = [
  {
    id: "basic-cultural-conditions",
    name: "Cultural Conditions",
    categories: [
      {
        id: "basic-light",
        name: "Light",
        options: [
          "Dappled Sunlight (Shade through upper canopy all day) ",
          "Deep shade (Less than 2 hours to no direct sunlight) ",
          "Full Sun (6 or more hours of direct sunlight a day)",
          "Partial Shade (Direct sunlight only part of the day, 2-6 hours)",
        ],
        icon: Sun,
      },
      {
        id: "basic-soil-texture",
        name: "Soil Texture",
        options: [
          "Clay",
          "Loam (Silt)",
          "Sand",
          "High Organic Matter",
          "Shallow Rocky",
        ],
        icon: Leaf,
      },
      {
        id: "basic-soil-ph",
        name: "Soil pH",
        options: ["Acid (<6.0)", "Neutral (6.0-8.0)", "Alkaline (>8.0)"],
        icon: Droplet,
      },
      {
        id: "basic-soil-drainage",
        name: "Soil Drainage",
        options: [
          "Frequent Standing Water",
          "Good Drainage",
          "Moist",
          "Occasional Flooding",
          "Occasionally Dry",
          "Occasionally Wet",
          "Very Dry",
        ],
        icon: Pipette,
      },
      {
        id: "basic-available-space-to-plant",
        name: "Available Space To Plant",
        options: [
          "Less than 12 inches",
          "12 inches-3 feet",
          "3 feet-6 feet",
          "6 feet-12 feet",
          "12-24 feet",
          "24-60 feet",
          "more than 60 feet",
        ],
        icon: Ruler,
      },
      {
        id: "basic-nc-region",
        name: "NC Region",
        options: ["Coastal", "Mountains", "Piedmont"],
        icon: Mountain,
      },
      {
        id: "basic-usda-plant-hardiness-zone",
        name: "USDA Plant Hardiness Zone",
        options: [
          "1a",
          "1b",
          "2a",
          "2b",
          "3a",
          "3b",
          "4a",
          "4b",
          "5a",
          "5b",
          "6a",
          "6b",
          "7a",
          "7b",
          "8a",
          "8b",
          "9a",
          "9b",
          "10a",
          "10b",
          "11a",
          "11b",
          "12a",
          "12b",
          "13a",
          "13b",
        ],
        icon: MapPin,
      },
    ],
    icon: Map,
  },
  {
    id: "basic-landscape",
    name: "Landscape",
    categories: [
      {
        id: "landscape-location",
        name: "Landscape Location",
        options: [
          "Coastal",
          "Container",
          "Hanging Baskets",
          "Houseplants",
          "Lawn",
          "Meadow",
          "Naturalized Area",
          "Near Septic",
          "Patio",
          "Pond",
          "Pool/Hardscape",
          "Recreational Play Area",
          "Riparian",
          "Rock Wall",
          "Slope/Bank",
          "Small Space",
          "Vertical Spaces",
          "Walkways",
          "Woodland",
        ],
        icon: MapPinHouse,
      },
    ],
    icon: TreePine,
  },
];

export const advancedFilters: FilterSection[] = [
  {
    id: "advanced-landscape",
    name: "Landscape",
    categories: [
      {
        id: "advanced-landscape-theme",
        name: "Landscape Theme",
        options: [
          "Asian Garden",
          "Butterfly Garden",
          "Children's Garden",
          "Cottage Garden",
          "Cutting Garden",
          "Drought Tolerant Garden",
          "Edible Garden",
          "English Garden",
          "Fairy Garden",
          "Garden for the Blind",
          "Native Garden",
          "Nighttime Garden",
          "Pollinator Garden",
          "Rain Garden",
          "Rock Garden",
          "Shade Garden",
          "Water Garden",
          "Winter Garden",
        ],
        icon: Flower,
      },
      {
        id: "advanced-landscape-design-feature",
        name: "Design Feature",
        options: [
          "Accent",
          "Barrier",
          "Border",
          "Flowering Tree",
          "Foundation Planting",
          "Hedge",
          "Mass Planting",
          "Screen/Privacy",
          "Security",
          "Shade Tree",
          "Small groups",
          "Small Tree",
          "Specimen",
          "Street Tree",
          "Understory Tree",
        ],
        icon: Eye,
      },
    ],
    icon: TreeDeciduous,
  },
  {
    id: "advanced-wildlife-resistance",
    name: "Wildlife and Resistance",
    categories: [
      {
        id: "advanced-attracts",
        name: "Attracts",
        options: [
          "Bats",
          "Bees",
          "Butterflies",
          "Frogs",
          "Hummingbirds",
          "Moths",
          "Pollinators",
          "Predatory Insects",
          "Reptiles",
          "Small Mammals",
          "Songbirds",
          "Specialized Bees",
        ],
        icon: Heart,
      },
      {
        id: "advanced-resistance-to-challenges",
        name: "Resistance To Challenges",
        options: [
          "Black Walnut",
          "Compaction",
          "Deer",
          "Diseases",
          "Drought",
          "Dry Soil",
          "Erosion",
          "Fire",
          "Foot Traffic",
          "Heat",
          "Heavy Shade",
          "Humidity",
          "Insect Pests",
          "Pollution",
          "Poor Soil",
          "Rabbits",
          "Salt",
          "Slugs",
          "Squirrels",
          "Storm Damage",
          "Urban Conditions",
          "Voles",
          "Wet Soil",
          "Wind",
        ],
        icon: ShieldCheck,
      },
      {
        id: "advanced-problems-to-exclude",
        name: "Problems to Exclude",
        options: [
          "Allelopathic",
          "Contact Dermatitis",
          "Frequent Disease Problems",
          "Frequent Insect Problems",
          "Invasive Species",
          "Malodorous",
          "Messy",
          "Poisonous to Humans",
          "Problem for Cats",
          "Problem for Children",
          "Problem for Dogs",
          "Problem for Horses",
          "Short-lived",
          "Spines/Thorns",
          "Weak Wood",
          "Weedy",
        ],
        icon: AlertTriangle,
      },
    ],
    icon: Shield,
  },
  {
    id: "advanced-whole-plant-traits",
    name: "Whole Plant Traits",
    categories: [
      {
        id: "advanced-plant-type",
        name: "Plant Type",
        options: [
          "Annual",
          "Bulb",
          "Carnivorous",
          "Cool Season Vegetable",
          "Edible",
          "Epiphyte",
          "Fern",
          "Ground Cover",
          "Herb",
          "Herbaceous Perennial",
          "Houseplant",
          "Mushroom",
          "Native Plant",
          "Ornamental Grasses and Sedges",
          "Perennial",
          "Poisonous",
          "Rose",
          "Shrub",
          "Succulent",
          "Tree",
          "Turfgrass",
          "Vegetable",
          "Vine",
          "Warm Season Vegetable",
          "Water Plant",
          "Weed",
          "Wildflower",
        ],
        icon: TreePine,
      },
      {
        id: "advanced-woody-plat-leaf-characteristics",
        name: "Woody Plant Leaf Characteristics",
        options: [
          "Broadleaf Evergreen",
          "Deciduous",
          "Needled Evergreen",
          "Semi-evergreen",
        ],
        icon: Leaf,
      },
      {
        id: "advanced-habit-form",
        name: "Habit/Form",
        options: [
          "Arching",
          "Ascending",
          "Broad",
          "Cascading",
          "Climbing",
          "Clumping",
          "Columnar",
          "Conical",
          "Creeping",
          "Dense",
          "Erect",
          "Horizontal",
          "Irregular",
          "Mounding",
          "Multi-stemmed",
          "Multi-trunked",
          "Open",
          "Oval",
          "Prostrate",
          "Pyramidal",
          "Rounded",
          "Spreading",
          "Vase",
          "Weeping",
        ],
        icon: Star,
      },
      {
        id: "advanced-growth-rate",
        name: "Growth Rate",
        options: ["Slow", "Medium", "Rapid"],
        icon: Clock,
      },
      {
        id: "advanced-maintenance",
        name: "Maintenance",
        options: ["High", "Low", "Medium"],
        icon: Activity,
      },
      {
        id: "advanced-texture",
        name: "Texture",
        options: ["Fine", "Medium", "Coarse"],
        icon: Hand,
      },
    ],
    icon: Leaf,
  },
  {
    id: "advanced-flowers",
    name: "Flowers",
    categories: [
      {
        id: "advanced-flower-color",
        name: "Flower Color",
        options: [
          "Black",
          "Blue",
          "Brown/Copper",
          "Cream/Tan",
          "Gold/Yellow",
          "Gray/Silver",
          "Green",
          "Insignificant",
          "Orange",
          "Pink",
          "Purple/Lavender",
          "Red/Burgundy",
          "Variegated",
          "White",
        ],
        icon: Paintbrush,
      },
      {
        id: "advanced-flower-value-to-gardener",
        name: "Flower Value To Gardener",
        options: [
          "Edible",
          "Fragrant",
          "Good Cut",
          "Good Dried",
          "Long Bloom Season",
          "Long-lasting",
          "Showy",
        ],
        icon: Heart,
      },
      {
        id: "advanced-flower-bloom-time",
        name: "Flower Bloom Time",
        options: ["Fall", "Spring", "Summer", "Winter"],
        icon: Sprout,
      },
    ],
    icon: Flower,
  },
  {
    id: "advanced-leaves",
    name: "Leaves",
    categories: [
      {
        id: "advanced-leaf-color",
        name: "Leaf Color",
        options: [
          "Black",
          "Blue",
          "Brown/Copper",
          "Cream/Tan",
          "Gold/Yellow",
          "Gray/Silver",
          "Green",
          "Insignificant",
          "Orange",
          "Pink",
          "Purple/Lavender",
          "Red/Burgundy",
          "Variegated",
          "White",
        ],
        icon: Paintbrush,
      },
      {
        id: "advanced-leaf-texture",
        name: "Leaf Texture",
        options: [
          "Fleshy",
          "Glossy",
          "Leathery",
          "Papery",
          "Prickly",
          "Rough",
          "Rubbery",
          "Slippery",
          "Smooth",
          "Soft",
          "Velvety",
          "Waxy",
        ],
        icon: Hand,
      },
      {
        id: "advanced-leaf-value-to-gardener",
        name: "Leaf Value To Gardener",
        options: [
          "Edible",
          "Fragrant",
          "Good Cut",
          "Good Dried",
          "Long-lasting",
          "Showy",
        ],
        icon: Heart,
      },
      {
        id: "advanced-deciduous-leaf-fall-color",
        name: "Deciduous Leaf Fall Color",
        options: [
          "Brown/Copper",
          "Cream/Tan",
          "Gold/Yellow",
          "Gray/Silver",
          "Insignificant",
          "Orange",
          "Pink",
          "Purple/Lavender",
          "Red/Burgundy",
        ],
        icon: Palette,
      },
    ],
    icon: Leaf,
  },
];

export const predefinedFilterSets = [
  {
    name: "Beginner Plants",
    filters: ["Full Sun", "Loam (Silt)", "Good Drainage", "Medium Maintenance"],
  },
  {
    name: "Indoor Plants",
    filters: ["Low Light", "Container", "Houseplants"],
  },
  {
    name: "Pollinator Garden",
    filters: [
      "Pollinator Garden",
      "Attracts: Pollinators",
      "Flower Bloom Time: Spring",
    ],
  },
  {
    name: "Raleigh Garden",
    filters: ["Piedmont", "Clay", "7b", "Drought Resistance"],
  },
];
